version: '3.3'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=distribuidora
      - POSTGRES_USER=gustavo
      - POSTGRES_PASSWORD=admin1234
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - 5050:80